curl -X POST \
  http://localhost:3000/api/pedidos \
  -H 'Content-Type: application/json' \
  -d '{
  "fechapedido": "2024-04-02",
  "subtotal": 91000,
  "descuento":9000,
  "iva": 9500,
  "totalpedido": 93500,
  "preciodomicilio": 9000,
  "estadopedido": "cancelado"
}